atlas_fc_mesh_path : ./OAI_analysis/data/atlas_FC_inner_mesh_world.ply
atlas_image : ./OAI_analysis/atlas/atlas_60_LEFT_baseline_NMI/atlas.nii.gz
atlas_tc_2d_map_path : ./OAI_analysis/data/TC_inner_embedded.npy
atlas_tc_mesh_path : ./OAI_analysis/data/atlas_TC_inner_mesh_world.ply
avsm_directory : /home/ssbehera/oai/easyreg
nifty_reg_directory : /home/ssbehera/oai/niftyreg/niftyreg-git/install/bin
oai_data_directory : /mnt/beegfs/uray/
oai_data_sheet : ./OAI_analysis/data/SEG_3D_DESS_allTmp.csv
oai_enrollees : ./OAI_analysis/data/EnrolleesTmp.txt
output_directory : /mnt/beegfs/ssbehera/results
overwrite : false
python_executable : /usr/bin/python3.6
seed : 2018
use_nifty_reg : true
