pipelinestages:
    - name: preprocess
      resource: CPU
    - name: segmentation
      resource: GPU
    - name: extractsurfacemesh
      resource: CPU
    - name: registerimagetoatlas
      resource: GPU
    - name: warpmesh
      resource: CPU
    - name: evalregistration
      resource: CPU
    - name: setatlas2dmap
      resource: CPU
    - name: computeatlas2dmap
      resource: CPU
    - name: projectthicknesstoatlas
      resource: CPU
    - name: projectthicknessto2d
      resource: CPU
