#
# This is how to do the build (and some other useful commands)
#
# To build requires access to the conda-forge, pytorchm and anaconda channels
# can be used with --debug flag
# conda build . -c pytorch -c conda-forge -c anaconda -c uncbiag
#
# to upload to the cloud
# anaconda login
# anaconda upload --user uncbiag easyreg
#
# Combined with travis, to auto-create conda packages and upload them to the conda cloud, tag them.

{% set name = "easyreg" %}

package:
  name: '{{ name|lower }}'
  version: {{ GIT_DESCRIBE_TAG }}

source:
  - git_url: .

requirements:
  build:
    - python ==3.7
    - setuptools
    - pip

  run:
    - python ==3.7
    - ipython
    - numpy >=1.17
    - future
    - scikit-image
    - cffi
    - itk
    - pytorch
    - pynrrd
    - torchvision
    - pandas
    - matplotlib
    - scipy
    - openpyxl
    - sphinx
    - progressbar2
    - h5py
    - SimpleITK
    - tensorboardX
    - blosc
    - ants
    - nibabel
    - webcolors
    - sklearn
    - gdown

#test:
#  imports:
#    - easyreg

about:
  home: https://github.com/uncbiag/easyreg
  license: Apache 2.0 license
  license_family: BSD
  license_file: LICENSE
  summary: 'Deep-learning-based image registration. Companion package to mermaid.'
  description: 'This image registration toolbox provides approaches to train and run deep-learning-based image registration networks based on the transformation models available within mermaid. It is written in pytorch allowing for easy prototyping of new approaches. To install include the conda-forge and the anaconda channels by executing: conda install -c pytorch -c conda-forge -c anaconda -c uncbiag easyreg'
  doc_url: 'https://easyreg.readthedocs.io/en/latest/'
  dev_url: 'https://github.com/uncbiag/easyreg'

extra:
  recipe-maintainers:
    - marcniethammer
    - hbgtjxzbbx

